version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout

      - run:
          name: install python dependencies
          command: |
            virtualenv env --no-site-packages
            source env/bin/activate
            pip install -r requirements.txt


  deploy:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout

      - run:
          name: install python dependencies
          command: |
            virtualenv env --no-site-packages
            source env/bin/activate
            pip install -r requirements.txt

      - run:
          name: verify git tag vs. version
          command: |
            source env/bin/activate
            python setup.py verify

      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = fernandosure" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

      - run:
          name: create packages
          command: |
            python setup.py sdist

      - run:
          name: upload to pypi
          command: |
            source env/bin/activate
            twine upload dist/*

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/